name: "Keep History Conventional"
description: "Keeps in the commits history only the commits that follows the Conventional Commit convention."
author: "mail@fabriziocacicia.com"

inputs:
  branch:
    description: 'The branch to keep conventional'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check Latest Commit Conventional
      uses: fabriziocacicia/check-latest-commit-conventional-action@v0.1.0
      id: check-conventional-commit
      continue-on-error: true
    - if: steps.check-conventional-commit.outcome == 'success'
      run: exit 0
      shell: bash
    - name: Move Latest Commit to PR
      if: steps.check-conventional-commit.outcome != 'success'
      uses: fabriziocacicia/move-latest-commit-to-pr-action@v0.3.0
      with:
        baseBranch: ${{ inputs.branch }}
        headBranch: keep_history_conventional
        prBody: |
          The commit $LATEST_COMMIT_HASH doesn't follow the [Conventional Commit convention](https://www.conventionalcommits.org/). 
          Because of that, it was removed from the history of the repository.
         
          Please, squash this PR updating the commit message so that it follows the convention.
          
          - Auto-generated by [keep-history-conventional][1]
    
          [1]: https://github.com/fabriziocacicia/keep-history-conventional

branding:
  icon: "mic"
  color: "black"
